import { Head, usePage } from '@inertiajs/react';

/**
 * A page's title and everything that describes it to something that is not a
 * browser: search results, a link pasted into Slack, a shared post.
 *
 * Every screen already had a `<Head title>`. None had a description, and the
 * application had no `og:` or `twitter:` tags at all — so every link to Clover,
 * anywhere, previewed as a bare URL with the site name and nothing else.
 *
 * ## Why one component rather than tags per page
 *
 * A title and a description are two halves of the same sentence, and kept
 * apart they drift: a page gets retitled and the description under it still
 * describes the old screen. Here they are one call, and a page cannot supply
 * one without the other.
 *
 * The `og:` and `twitter:` pairs are derived rather than authored. They said
 * the same thing as the title and description on every page that had them, so
 * asking each screen for four more strings would be asking for four more
 * chances to disagree.
 *
 * ## head-key
 *
 * Inertia dedupes head elements by `head-key`. Without one, navigating between
 * two pages leaves both descriptions in the document and a crawler reads
 * whichever it likes. Every tag here carries one.
 */
type PageMetaProps = {
    /** Shown in the tab, and as the headline of every link preview. */
    title: string;
    /**
     * One or two sentences on what this screen is. Written for someone who has
     * not seen it, because that is who reads it — in a search result, or under
     * a link somebody pasted.
     */
    description: string;
    /**
     * `article` for a single thread, which is the only thing here that is one.
     * Everything else is a page of a website.
     */
    type?: 'website' | 'article';
};

/**
 * The social card, generated by `clover:og-image` and committed. One image for
 * the whole site: per-page cards would need a font stack GD cannot load and an
 * image route to render them, to say in a picture what the description beside
 * it already says in words.
 */
const OG_IMAGE = '/og.png';

const SITE_NAME = 'Clover';

function PageMeta({ title, description, type = 'website' }: PageMetaProps) {
    const page = usePage<{ appUrl: string }>();

    /* Absolute, because a relative `og:url` is not a URL to anything. The
       origin comes from the server rather than from `window.location`, which
       does not exist while Inertia is rendering this on the server. */
    const url = `${page.props.appUrl}${page.url}`;

    return (
        <Head title={title}>
            <meta
                head-key="description"
                name="description"
                content={description}
            />

            <meta
                head-key="og:site_name"
                property="og:site_name"
                content={SITE_NAME}
            />
            <meta head-key="og:type" property="og:type" content={type} />
            <meta head-key="og:title" property="og:title" content={title} />
            <meta
                head-key="og:description"
                property="og:description"
                content={description}
            />
            <meta head-key="og:url" property="og:url" content={url} />
            <meta
                head-key="og:image"
                property="og:image"
                content={`${page.props.appUrl}${OG_IMAGE}`}
            />

            {/* `summary_large_image` rather than `summary`: the card is 1200x630
                and a `summary` crops it to a square thumbnail, which cuts the
                headline in half. */}
            <meta
                head-key="twitter:card"
                name="twitter:card"
                content="summary_large_image"
            />
            <meta
                head-key="twitter:title"
                name="twitter:title"
                content={title}
            />
            <meta
                head-key="twitter:description"
                name="twitter:description"
                content={description}
            />
            <meta
                head-key="twitter:image"
                name="twitter:image"
                content={`${page.props.appUrl}${OG_IMAGE}`}
            />
        </Head>
    );
}

export { PageMeta };
export type { PageMetaProps };
